# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches-ignore:
      - "dependabot/*"

jobs:

  deploy_dev:
    name: Deploy to Development
    if: ${{ github.ref == 'refs/heads/development' }}
    runs-on: ubuntu-latest
    environment: Development

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Set output
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        #if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Npx SST Deploy Dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npx deploy --stage dev

  deploy_stag:
    name: Deploy to Staging
    if: ${{ github.ref == 'refs/heads/staging' }}
    needs: [deploy_dev]
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - name: Npx SST Deploy Stag
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npm run deploy --stage stag

  deploy_prod:
    name: Deploy to Production
    if: ${{ github.ref == 'refs/heads/production' }}
    needs: [deploy_stag]
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Npx SST Deploy Prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npm run deploy --stage prod
